### PR TITLE
Do not generate helper, include Draper gem instead

### PR DESCRIPTION
**Pull request by paulspringett**

### CODE REVIEW

**Comment by paulspringett** [comment]
@markjs @hecticjeff what are your thoughts on this? I can't remember the last time I wrote a helper method!

**Comment by chrismytton** [comment]
Hell yea. :shipit: :rocket:

**Comment by markjs** [comment]
Not generating helpers: :+1: 
Draper: Don't really have an opinion.

**Comment by paulspringett** [comment]
Squirrel on a rocket...!

@markjs hmm I think without helpers an alternative way of decorating the view should be provided by default.

**Pull request merged**
